[project]
name = "electric-scraper"
version = "0.1.0"
description = "Tools to scrape electrical component data from online sources (with MCP server)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "selenium>=4.34.2",
]
